# vim: ft=yaml
---
driver:
  name: vagrant
  customize: 
    memory: 1024

provisioner:
  omnibus_cachier: true
  name: salt_solo
  is_file_root: true
  salt_copy_filter:
    - .kitchen
    - .git
    - .vagrant
  state_top:
    base:
      "*":
        - snmp

platforms:
  - name: bento/ubuntu-16.04

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        snmp.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - snmp

